$(addprefix SOURCES_PATH, \
noc_block_qpsk.v \
loop_filter.v  \
polar_costas.v \
BitSync.v \
syncout.v \
clktrans.v \
differpd.v \
monostable.v \
controldivfreq.v \
keep_one_in_n_desample.v \
keep_one_in_n_zip.v \
) \
